<?php echo $this->doctype(); ?>
<html>
<head>
	<?php echo $this->headTitle; ?>		
	<?php echo $this->headScript; ?>		
	<?php echo $this->headLink; ?>
</head>
<body>
	<div id="header"> 
		<img src="images/logo.png" />
	</div>
	<div id="menu">
		<?php echo ( $this->menu ) ? $this->action('index','nav') : ''; ?>
	</div>
	<div id="content">
		<div id="messages"><?php echo $this->swfFlashMessenger()?></div>
		<?php echo $this->layout()->content ?>	
	</div>
	<div id="footer">
	</div>
</body>
</html>
